name: movie_streaming_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  http: ^1.4.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  pinput: ^5.0.1
  expandable_page_view: ^1.0.17
  flutter_html: ^3.0.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  rename: ^3.1.0
  connectivity: ^3.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/launcher_icon.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true